#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/calories?serverTimezone=UTC
#    username: calories
#    password: calories
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:caloriesdb
    username: calories
    password: calories
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update


server:
  port: 8090